"""
Corrector node for fixing invalid Cypher queries using LLM feedback.

Based on LangGraph documentation: https://python.langchain.com/docs/tutorials/graph/#advanced-implementation-with-langgraph
"""

from typing import Any

from langchain_core.language_models import BaseChatModel
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

from neo4j_agent.state import WorkflowState

# =============================================================================
# Correction Prompt Templates
# =============================================================================


def create_correction_prompt_template() -> ChatPromptTemplate:
    """
    Create a Text2Cypher query correction prompt template.

    Returns:
        ChatPromptTemplate: The prompt template
    """
    return ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """You are a Cypher expert fixing queries that have OBJECTIVE errors.

Your job: Fix syntax errors, undefined variables, and logical bugs.
NOT your job: Remove or change filters, restructure queries, or second-guess design decisions.

The original query was generated by a context-aware system.
Preserve its structure and logic unless fixing a clear error.""",
            ),
            (
                "human",
                """Fix ONLY the specific errors provided. Do not make other changes.

Schema (use EXACT case-sensitive names):
{schema}

Question: {question}

Current query:
{cypher}

Errors to fix:
{errors}

Guidelines:
1. Fix undefined variables, syntax errors, or schema mismatches
2. Preserve WHERE clause filters and conditions (they may be from conversation context)
3. Preserve query structure and logic
4. Use exact label/property names from schema (case-sensitive)
5. Only change what's broken

Return ONLY the corrected Cypher query (no explanations, no backticks, no preamble).

Corrected Cypher statement: """,
            ),
        ]
    )


# =============================================================================
# Corrector Node Factory
# =============================================================================


def create_corrector_node(llm: BaseChatModel, schema: dict[str, Any]):
    """Factory to create the Cypher correction node.

    Uses LLM to fix invalid Cypher queries based on error messages.

    Args:
        llm: Language model instance
        schema: Neo4j schema dictionary (with "schema" key containing string representation)

    Returns:
        Corrector node function
    """
    correction_prompt = create_correction_prompt_template()
    correction_chain = correction_prompt | llm | StrOutputParser()

    def correct_cypher(state: WorkflowState) -> dict:
        """Correct an invalid Cypher query.

        Args:
            state: Current workflow state

        Returns:
            State updates with corrected Cypher query and incremented retry count
        """
        from neo4j_agent.utils.state_helpers import (
            append_to_query_trace,
            create_text2cypher_update,
            get_text2cypher_output,
        )

        question = state["question"]
        error = state.get("error", "")

        text2cypher_output = get_text2cypher_output(state)
        cypher_query = text2cypher_output.get("cypher_query", "")
        retry_count = text2cypher_output.get("retry_count", 0)

        # Schema is already a formatted string from get_schema()

        # Generate corrected Cypher
        corrected_cypher = correction_chain.invoke(
            {
                "question": question,
                "cypher": cypher_query,
                "errors": error,
                "schema": schema,  # Use schema string directly
            }
        )

        # Increment retry count to track correction attempts
        # This is used by the subgraph routing to determine if max retries reached
        new_retry_count = retry_count + 1

        # Append corrected query to trace
        trace = append_to_query_trace(
            state,
            attempt=new_retry_count + 1,  # Next attempt number
            query=corrected_cypher,
            source="corrector",
            validation_errors=[],  # Validator will populate this
        )

        # Return corrected query and updated retry count
        # Note: error field is NOT cleared here - validator will clear it if correction is valid
        # Clear failed_at_node since we're attempting a correction
        # (validator will re-set if still failing)
        return create_text2cypher_update(
            cypher_query=corrected_cypher,
            retry_count=new_retry_count,
            query_generation_trace=trace,
            failed_at_node=None,  # Clear failure marker - validator will re-set if correction fails
        )

    return correct_cypher
